"""init db

Revision ID: 2b5b1df34956
Revises: 3b34467869a6
Create Date: 2026-04-19 14:08:56.186740

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2b5b1df34956'
down_revision: Union[str, Sequence[str], None] = '3b34467869a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('DROP TABLE IF EXISTS "DieuKienTienQuyet"')
    op.add_column('DangKy', sa.Column('MaHP', sa.String(), nullable=False))
    op.add_column('DangKy', sa.Column('MaHocKy', sa.String(), nullable=False))
    op.add_column('DangKy', sa.Column('MaLich', sa.String(), nullable=False))
    op.drop_constraint(op.f('uq_dk_sv_lophp'), 'DangKy', type_='unique')
    op.create_unique_constraint('uq_dk_sv_hp_hk', 'DangKy', ['MaSV', 'MaHP', 'MaHocKy'])
    op.create_foreign_key(None, 'DangKy', 'HocKy', ['MaHocKy'], ['MaHocKy'])
    op.create_foreign_key(None, 'DangKy', 'HocPhan', ['MaHP'], ['MaHP'])
    op.create_foreign_key(None, 'DangKy', 'LichHoc', ['MaLich'], ['MaLich'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'DangKy', type_='foreignkey')
    op.drop_constraint(None, 'DangKy', type_='foreignkey')
    op.drop_constraint(None, 'DangKy', type_='foreignkey')
    op.drop_constraint('uq_dk_sv_hp_hk', 'DangKy', type_='unique')
    op.create_unique_constraint(op.f('uq_dk_sv_lophp'), 'DangKy', ['MaSV', 'MaLopHP'], postgresql_nulls_not_distinct=False)
    op.drop_column('DangKy', 'MaLich')
    op.drop_column('DangKy', 'MaHocKy')
    op.drop_column('DangKy', 'MaHP')
    op.create_table('DieuKienTienQuyet',
    sa.Column('MaHP', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('MaHP_TienQuyet', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['MaHP'], ['HocPhan.MaHP'], name=op.f('DieuKienTienQuyet_MaHP_fkey')),
    sa.ForeignKeyConstraint(['MaHP_TienQuyet'], ['HocPhan.MaHP'], name=op.f('DieuKienTienQuyet_MaHP_TienQuyet_fkey')),
    sa.PrimaryKeyConstraint('MaHP', 'MaHP_TienQuyet', name=op.f('uq_tienquyet_mahp'))
    )
    # ### end Alembic commands ###
