"""add_lan_thu_to_nhatky

Revision ID: 6e4e4d72ba90
Revises: a8c0f8b6bb89
Create Date: 2026-05-04 22:35:45.764020

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e4e4d72ba90'
down_revision: Union[str, Sequence[str], None] = 'a8c0f8b6bb89'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('NhatKyThaoTac', sa.Column('LanThu', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('NhatKyThaoTac', 'LanThu')
    # ### end Alembic commands ###
