"""Add NhatKyThaoTac Enum

Revision ID: bbc6cbefc7ae
Revises: 84e5a1900962
Create Date: 2026-04-29 18:52:56.971820

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bbc6cbefc7ae'
down_revision: Union[str, Sequence[str], None] = '84e5a1900962'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('NhatKyThaoTac',
    sa.Column('ID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('MaGiaoTac', sa.String(length=50), nullable=False),
    sa.Column('MaLopHP', sa.String(length=20), nullable=False),
    sa.Column('MaSV', sa.String(length=20), nullable=False),
    sa.Column('Buoc', sa.Enum('BEGIN', 'DA_KHOA', 'KIEM_TRA_SI_SO', 'INSERT', 'COMMIT', 'ROLLBACK', name='buocgiaotac'), nullable=False),
    sa.Column('ChiTiet', sa.Text(), nullable=True),
    sa.Column('ThoiGian', sa.DateTime(), nullable=False),
    sa.Column('TrangThai', sa.Enum('DANG_CHAY', 'THANH_CONG', 'THAT_BAI', name='trangthaigiaotac'), nullable=False),
    sa.PrimaryKeyConstraint('ID')
    )
    op.create_index(op.f('ix_NhatKyThaoTac_ID'), 'NhatKyThaoTac', ['ID'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_NhatKyThaoTac_ID'), table_name='NhatKyThaoTac')
    op.drop_table('NhatKyThaoTac')
    # ### end Alembic commands ###
