"""remove_lan_thu

Revision ID: d1443d349072
Revises: 6e4e4d72ba90
Create Date: 2026-05-04 22:44:17.201551

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd1443d349072'
down_revision: Union[str, Sequence[str], None] = '6e4e4d72ba90'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('NhatKyThaoTac', 'LanThu')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('NhatKyThaoTac', sa.Column('LanThu', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
