"""remove_enrollment_log_model

Revision ID: 03e4fa09cd3c
Revises: 1cb93220ad02
Create Date: 2026-05-04 22:13:01.529295

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '03e4fa09cd3c'
down_revision: Union[str, Sequence[str], None] = '1cb93220ad02'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_DangKy_Log_LogId'), table_name='DangKy_Log')
    op.drop_table('DangKy_Log')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('DangKy_Log',
    sa.Column('LogId', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('userId', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('MaLopHP', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('MaHP', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('Action', postgresql.ENUM('REGISTER', 'CANCEL', 'SWITCH', name='enrollmentaction'), autoincrement=False, nullable=False),
    sa.Column('TargetSite', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('Status', postgresql.ENUM('SUCCESS', 'FAILED', 'PENDING', name='logstatus'), autoincrement=False, nullable=True),
    sa.Column('Message', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('Timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['userId'], ['users.userId'], name=op.f('DangKy_Log_userId_fkey')),
    sa.PrimaryKeyConstraint('LogId', name=op.f('DangKy_Log_pkey'))
    )
    op.create_index(op.f('ix_DangKy_Log_LogId'), 'DangKy_Log', ['LogId'], unique=False)
    # ### end Alembic commands ###
