"""init db

Revision ID: a6767a6ff69a
Revises: 
Create Date: 2026-04-19 04:16:55.498222

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a6767a6ff69a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('CoSo',
    sa.Column('MaCoSo', sa.String(), nullable=False),
    sa.Column('TenCoSo', sa.String(), nullable=False),
    sa.Column('DiaChi', sa.String(), nullable=True),
    sa.Column('SoDienThoai', sa.String(), nullable=True),
    sa.Column('Email', sa.String(), nullable=True),
    sa.Column('NgayThanhLap', sa.Date(), nullable=True),
    sa.Column('TrangThai', sa.Enum('HoatDong', 'NgungHoatDong', name='generalstatus'), nullable=True),
    sa.PrimaryKeyConstraint('MaCoSo')
    )
    op.create_index(op.f('ix_CoSo_MaCoSo'), 'CoSo', ['MaCoSo'], unique=False)
    op.create_table('HocKy',
    sa.Column('MaHocKy', sa.String(), nullable=False),
    sa.Column('NamHoc', sa.String(), nullable=False),
    sa.Column('KySo', sa.Integer(), nullable=False),
    sa.Column('NgayBatDau', sa.Date(), nullable=True),
    sa.Column('NgayKetThuc', sa.Date(), nullable=True),
    sa.Column('TrangThaiHocKy', sa.Enum('SapMo', 'DangDangKy', 'DangHoc', 'DaKetThuc', name='semesterstatus'), nullable=False),
    sa.PrimaryKeyConstraint('MaHocKy')
    )
    op.create_index(op.f('ix_HocKy_MaHocKy'), 'HocKy', ['MaHocKy'], unique=False)
    op.create_table('Khoa',
    sa.Column('MaKhoa', sa.String(), nullable=False),
    sa.Column('TenKhoa', sa.String(), nullable=False),
    sa.Column('MoTa', sa.String(), nullable=True),
    sa.Column('NgayThanhLap', sa.Date(), nullable=True),
    sa.Column('TrangThai', sa.Enum('HoatDong', 'NgungHoatDong', name='generalstatus'), nullable=True),
    sa.PrimaryKeyConstraint('MaKhoa'),
    sa.UniqueConstraint('TenKhoa')
    )
    op.create_index(op.f('ix_Khoa_MaKhoa'), 'Khoa', ['MaKhoa'], unique=False)
    op.create_table('users',
    sa.Column('userId', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('SinhVien', 'GiangVien', 'Admin', name='userrole'), nullable=False),
    sa.Column('MaCoSo', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('Active', 'Inactive', 'Locked', name='userstatus'), nullable=True),
    sa.Column('NgayTao', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('userId'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_index(op.f('ix_users_userId'), 'users', ['userId'], unique=False)
    op.create_table('GiangVien',
    sa.Column('MaGV', sa.String(), nullable=False),
    sa.Column('userId', sa.String(), nullable=False),
    sa.Column('Ho', sa.String(), nullable=False),
    sa.Column('Ten', sa.String(), nullable=False),
    sa.Column('NgaySinh', sa.Date(), nullable=True),
    sa.Column('GioiTinh', sa.Enum('Nam', 'Nu', 'Khac', name='genders'), nullable=True),
    sa.Column('HocVi', sa.String(), nullable=True),
    sa.Column('HocHam', sa.String(), nullable=True),
    sa.Column('SDT', sa.String(), nullable=True),
    sa.Column('DiaChi', sa.String(), nullable=True),
    sa.Column('MaCoSo', sa.String(), nullable=False),
    sa.Column('MaKhoa', sa.String(), nullable=True),
    sa.Column('TrangThai', sa.Enum('DangCongTac', 'TamNghi', 'NghiViec', name='teacherstatus'), nullable=True),
    sa.Column('NgayVaoLam', sa.Date(), nullable=True),
    sa.Column('NgayTao', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['userId'], ['users.userId'], ),
    sa.PrimaryKeyConstraint('MaGV'),
    sa.UniqueConstraint('userId')
    )
    op.create_index(op.f('ix_GiangVien_MaGV'), 'GiangVien', ['MaGV'], unique=False)
    op.create_table('HocPhan',
    sa.Column('MaHP', sa.String(), nullable=False),
    sa.Column('TenHP', sa.String(), nullable=False),
    sa.Column('SoTinChi', sa.Integer(), nullable=False),
    sa.Column('SoTietLyThuyet', sa.Integer(), nullable=False),
    sa.Column('SoTietThucHanh', sa.Integer(), nullable=False),
    sa.Column('LoaiHocPhan', sa.Enum('BatBuoc', 'TuChon', name='coursetype'), nullable=False),
    sa.Column('MaKhoa', sa.String(), nullable=False),
    sa.Column('MoTa', sa.String(), nullable=True),
    sa.Column('TrangThai', sa.Enum('HoatDong', 'TamDung', 'HuyBo', name='coursestatus'), nullable=False),
    sa.Column('NgayTao', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['MaKhoa'], ['Khoa.MaKhoa'], ),
    sa.PrimaryKeyConstraint('MaHP')
    )
    op.create_index(op.f('ix_HocPhan_MaHP'), 'HocPhan', ['MaHP'], unique=False)
    op.create_table('PhongHoc',
    sa.Column('MaPhong', sa.String(), nullable=False),
    sa.Column('TenPhong', sa.String(), nullable=False),
    sa.Column('ToaNha', sa.String(), nullable=True),
    sa.Column('Tang', sa.Integer(), nullable=True),
    sa.Column('SucChua', sa.Integer(), nullable=False),
    sa.Column('LoaiPhong', sa.Enum('LyThuyet', 'ThucHanh', 'PhongMay', 'Khac', name='roomtype'), nullable=False),
    sa.Column('MaCoSo', sa.String(), nullable=False),
    sa.Column('TrangThai', sa.Enum('HoatDong', 'BaoTri', 'NgungSuDung', name='roomstatus'), nullable=False),
    sa.Column('NgayTao', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['MaCoSo'], ['CoSo.MaCoSo'], ),
    sa.PrimaryKeyConstraint('MaPhong')
    )
    op.create_index(op.f('ix_PhongHoc_MaPhong'), 'PhongHoc', ['MaPhong'], unique=False)
    op.create_table('SinhVien',
    sa.Column('MaSV', sa.String(), nullable=False),
    sa.Column('userId', sa.String(), nullable=False),
    sa.Column('Ho', sa.String(), nullable=False),
    sa.Column('Ten', sa.String(), nullable=False),
    sa.Column('NgaySinh', sa.Date(), nullable=True),
    sa.Column('GioiTinh', sa.Enum('Nam', 'Nu', 'Khac', name='genders'), nullable=True),
    sa.Column('SDT', sa.String(), nullable=True),
    sa.Column('DiaChi', sa.String(), nullable=True),
    sa.Column('MaCoSo', sa.String(), nullable=False),
    sa.Column('MaKhoa', sa.String(), nullable=True),
    sa.Column('TrangThai', sa.Enum('DangHoc', 'BaoLuu', 'ThoiHoc', 'TotNghiep', name='studentstatus'), nullable=True),
    sa.Column('NgayNhapHoc', sa.Date(), nullable=True),
    sa.Column('NgayTao', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['userId'], ['users.userId'], ),
    sa.PrimaryKeyConstraint('MaSV'),
    sa.UniqueConstraint('userId')
    )
    op.create_index(op.f('ix_SinhVien_MaSV'), 'SinhVien', ['MaSV'], unique=False)
    op.create_table('LopHocPhan',
    sa.Column('MaLopHP', sa.String(), nullable=False),
    sa.Column('MaHP', sa.String(), nullable=False),
    sa.Column('MaHocKy', sa.String(), nullable=False),
    sa.Column('MaCoSo', sa.String(), nullable=False),
    sa.Column('MaGV', sa.String(), nullable=False),
    sa.Column('TenLopHP', sa.String(), nullable=True),
    sa.Column('SiSoToiDa', sa.Integer(), nullable=False),
    sa.Column('SiSoHienTai', sa.Integer(), nullable=False),
    sa.Column('HinhThucHoc', sa.Enum('Offline', 'Online', 'Hybrid', name='studyform'), nullable=False),
    sa.Column('TrangThaiLop', sa.Enum('Mo', 'Dong', 'Huy', name='classsectionstatus'), nullable=False),
    sa.Column('NgayTao', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['MaCoSo'], ['CoSo.MaCoSo'], ),
    sa.ForeignKeyConstraint(['MaGV'], ['GiangVien.MaGV'], ),
    sa.ForeignKeyConstraint(['MaHP'], ['HocPhan.MaHP'], ),
    sa.ForeignKeyConstraint(['MaHocKy'], ['HocKy.MaHocKy'], ),
    sa.PrimaryKeyConstraint('MaLopHP')
    )
    op.create_index(op.f('ix_LopHocPhan_MaLopHP'), 'LopHocPhan', ['MaLopHP'], unique=False)
    op.create_table('DangKy',
    sa.Column('MaDangKy', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('MaSV', sa.String(), nullable=False),
    sa.Column('MaLopHP', sa.String(), nullable=False),
    sa.Column('NgayDangKy', sa.DateTime(), nullable=False),
    sa.Column('TrangThaiDangKy', sa.Enum('DaDangKy', 'HoanThanh', 'DaHuy', name='enrollmentstatus'), nullable=False),
    sa.Column('LanDangKy', sa.Integer(), nullable=False),
    sa.Column('GhiChu', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['MaLopHP'], ['LopHocPhan.MaLopHP'], ),
    sa.ForeignKeyConstraint(['MaSV'], ['SinhVien.MaSV'], ),
    sa.PrimaryKeyConstraint('MaDangKy'),
    sa.UniqueConstraint('MaSV', 'MaLopHP', name='uq_dk_sv_lophp')
    )
    op.create_index(op.f('ix_DangKy_MaDangKy'), 'DangKy', ['MaDangKy'], unique=False)
    op.create_table('LichHoc',
    sa.Column('MaLich', sa.String(), nullable=False),
    sa.Column('MaLopHP', sa.String(), nullable=False),
    sa.Column('MaPhong', sa.String(), nullable=False),
    sa.Column('ThuTrongTuan', sa.Integer(), nullable=False),
    sa.Column('TietBatDau', sa.Integer(), nullable=False),
    sa.Column('SoTiet', sa.Integer(), nullable=False),
    sa.Column('NgayBatDau', sa.Date(), nullable=True),
    sa.Column('NgayKetThuc', sa.Date(), nullable=True),
    sa.Column('GhiChu', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['MaLopHP'], ['LopHocPhan.MaLopHP'], ),
    sa.ForeignKeyConstraint(['MaPhong'], ['PhongHoc.MaPhong'], ),
    sa.PrimaryKeyConstraint('MaLich')
    )
    op.create_index(op.f('ix_LichHoc_MaLich'), 'LichHoc', ['MaLich'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_LichHoc_MaLich'), table_name='LichHoc')
    op.drop_table('LichHoc')
    op.drop_index(op.f('ix_DangKy_MaDangKy'), table_name='DangKy')
    op.drop_table('DangKy')
    op.drop_index(op.f('ix_LopHocPhan_MaLopHP'), table_name='LopHocPhan')
    op.drop_table('LopHocPhan')
    op.drop_index(op.f('ix_SinhVien_MaSV'), table_name='SinhVien')
    op.drop_table('SinhVien')
    op.drop_index(op.f('ix_PhongHoc_MaPhong'), table_name='PhongHoc')
    op.drop_table('PhongHoc')
    op.drop_index(op.f('ix_HocPhan_MaHP'), table_name='HocPhan')
    op.drop_table('HocPhan')
    op.drop_index(op.f('ix_GiangVien_MaGV'), table_name='GiangVien')
    op.drop_table('GiangVien')
    op.drop_index(op.f('ix_users_userId'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_Khoa_MaKhoa'), table_name='Khoa')
    op.drop_table('Khoa')
    op.drop_index(op.f('ix_HocKy_MaHocKy'), table_name='HocKy')
    op.drop_table('HocKy')
    op.drop_index(op.f('ix_CoSo_MaCoSo'), table_name='CoSo')
    op.drop_table('CoSo')
    # ### end Alembic commands ###
