"""sync_log_enums

Revision ID: 8f3f2cb9cc0f
Revises: eea5f2ff5d9d
Create Date: 2026-05-11 16:02:04.607512

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8f3f2cb9cc0f'
down_revision: Union[str, Sequence[str], None] = 'eea5f2ff5d9d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Cập nhật Enum BuocGiaoTac (Postgres Enum require manual ADD VALUE)
    # Sử dụng commit để có thể thực hiện ADD VALUE trong Postgres
    op.execute("COMMIT")
    for value in ["KIEM_TRA_SO_BO", "KHOA_PHAN_TAN", "KHOA_LOP_HP_DB", "KHOA_DANG_KY_CU", "KIEM_TRA_SI_SO_CUOI", "PRE_COMMIT"]:
        op.execute(f"ALTER TYPE buocgiaotac ADD VALUE IF NOT EXISTS '{value}'")
    
    op.drop_index(op.f('ix_DangKy_Log_LogId'), table_name='DangKy_Log')
    op.drop_table('DangKy_Log')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('DangKy_Log',
    sa.Column('LogId', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('userId', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('MaLopHP', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('MaHP', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('Action', postgresql.ENUM('REGISTER', 'CANCEL', 'SWITCH', name='enrollmentaction'), autoincrement=False, nullable=False),
    sa.Column('TargetSite', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('Status', postgresql.ENUM('SUCCESS', 'FAILED', 'PENDING', name='logstatus'), autoincrement=False, nullable=True),
    sa.Column('Message', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('Timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['userId'], ['users.userId'], name=op.f('DangKy_Log_userId_fkey')),
    sa.PrimaryKeyConstraint('LogId', name=op.f('DangKy_Log_pkey'))
    )
    op.create_index(op.f('ix_DangKy_Log_LogId'), 'DangKy_Log', ['LogId'], unique=False)
    # ### end Alembic commands ###
