"""Trung

Revision ID: b44da7211289
Revises: 4e1c5e611860
Create Date: 2026-04-24 22:50:37.932906

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b44da7211289'
down_revision: Union[str, Sequence[str], None] = '4e1c5e611860'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('DangKy_Log',
    sa.Column('LogId', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('userId', sa.String(), nullable=False),
    sa.Column('MaLopHP', sa.String(), nullable=False),
    sa.Column('MaHP', sa.String(), nullable=False),
    sa.Column('Action', sa.Enum('REGISTER', 'CANCEL', 'SWITCH', name='enrollmentaction'), nullable=False),
    sa.Column('TargetSite', sa.String(), nullable=False),
    sa.Column('Status', sa.Enum('SUCCESS', 'FAILED', 'PENDING', name='logstatus'), nullable=True),
    sa.Column('Message', sa.String(), nullable=True),
    sa.Column('Timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['userId'], ['users.userId'], ),
    sa.PrimaryKeyConstraint('LogId')
    )
    op.create_index(op.f('ix_DangKy_Log_LogId'), 'DangKy_Log', ['LogId'], unique=False)
    op.execute('DROP TABLE IF EXISTS "DieuKienTienQuyet"')
    op.add_column('DangKy', sa.Column('userId', sa.String(), nullable=False))
    op.alter_column('DangKy', 'MaSV',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint(op.f('uq_dk_sv_hp_hk'), 'DangKy', type_='unique')
    op.create_unique_constraint('uq_dk_user_hp_hk', 'DangKy', ['userId', 'MaHP', 'MaHocKy'])
    op.drop_constraint(op.f('DangKy_MaSV_fkey'), 'DangKy', type_='foreignkey')
    op.drop_constraint(op.f('DangKy_MaLich_fkey'), 'DangKy', type_='foreignkey')
    op.create_foreign_key(None, 'DangKy', 'users', ['userId'], ['userId'])
    op.drop_column('DangKy', 'MaLich')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('DangKy', sa.Column('MaLich', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'DangKy', type_='foreignkey')
    op.create_foreign_key(op.f('DangKy_MaLich_fkey'), 'DangKy', 'LichHoc', ['MaLich'], ['MaLich'])
    op.create_foreign_key(op.f('DangKy_MaSV_fkey'), 'DangKy', 'SinhVien', ['MaSV'], ['MaSV'])
    op.drop_constraint('uq_dk_user_hp_hk', 'DangKy', type_='unique')
    op.create_unique_constraint(op.f('uq_dk_sv_hp_hk'), 'DangKy', ['MaSV', 'MaHP', 'MaHocKy'], postgresql_nulls_not_distinct=False)
    op.alter_column('DangKy', 'MaSV',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('DangKy', 'userId')
    op.create_table('DieuKienTienQuyet',
    sa.Column('MaHP', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('MaHP_TienQuyet', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['MaHP'], ['HocPhan.MaHP'], name=op.f('DieuKienTienQuyet_MaHP_fkey')),
    sa.ForeignKeyConstraint(['MaHP_TienQuyet'], ['HocPhan.MaHP'], name=op.f('DieuKienTienQuyet_MaHP_TienQuyet_fkey')),
    sa.PrimaryKeyConstraint('MaHP', 'MaHP_TienQuyet', name=op.f('uq_tienquyet_mahp'))
    )
    op.drop_index(op.f('ix_DangKy_Log_LogId'), table_name='DangKy_Log')
    op.drop_table('DangKy_Log')
    # ### end Alembic commands ###
