"""add_userId_MaHP_MaHocKy_to_DangKy

Revision ID: c6083e14140f
Revises: 4180c3fd9ee3
Create Date: 2026-05-22 01:03:49.871007

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c6083e14140f'
down_revision: Union[str, Sequence[str], None] = '4180c3fd9ee3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('DangKyLog')
    op.drop_index(op.f('idx_tienquyet_mahp'), table_name='TienQuyet')
    op.drop_index(op.f('idx_tienquyet_tq'), table_name='TienQuyet')
    op.drop_table('TienQuyet')
    op.drop_table('AuditLog')
    op.alter_column('CoSo', 'MaCoSo',
               existing_type=sa.VARCHAR(length=10),
               comment=None,
               existing_comment='Mã cơ sở',
               existing_nullable=False)
    op.alter_column('CoSo', 'TenCoSo',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='Tên cơ sở',
               existing_nullable=False)
    op.alter_column('CoSo', 'DiaChi',
               existing_type=sa.VARCHAR(length=200),
               nullable=True,
               comment=None,
               existing_comment='Địa chỉ cơ sở')
    op.alter_column('CoSo', 'SoDienThoai',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='Số điện thoại',
               existing_nullable=True)
    op.alter_column('CoSo', 'Email',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='Email cơ sở',
               existing_nullable=True)
    op.alter_column('CoSo', 'NgayThanhLap',
               existing_type=sa.DATE(),
               comment=None,
               existing_comment='Ngày thành lập',
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_DATE'))
    op.alter_column('CoSo', 'TrangThai',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('HoatDong', 'NgungHoatDong', name='generalstatus'),
               comment=None,
               existing_comment='Trạng thái: HoatDong, BaoTri, NgungSuDung',
               existing_nullable=True,
               existing_server_default=sa.text("'HoatDong'::character varying"))
    op.drop_constraint(op.f('CoSo_Email_key'), 'CoSo', type_='unique')
    op.create_index(op.f('ix_CoSo_MaCoSo'), 'CoSo', ['MaCoSo'], unique=False)
    op.drop_table_comment(
        'CoSo',
        existing_comment='Thông tin cơ sở đào tạo - NHÂN BẢN toàn phần tại cả 3 site',
        schema=None
    )
    op.alter_column('DangKy', 'MaDangKy',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Mã đăng ký',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('DangKy', 'userId',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('DangKy', 'MaSV',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               comment=None,
               existing_comment='Sinh viên đăng ký')
    op.alter_column('DangKy', 'MaLopHP',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='Lớp học phần đăng ký',
               existing_nullable=False)
    op.alter_column('DangKy', 'MaHP',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('DangKy', 'MaHocKy',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('DangKy', 'NgayDangKy',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               comment=None,
               existing_comment='Thời điểm đăng ký',
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('DangKy', 'TrangThaiDangKy',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('DaDangKy', 'HoanThanh', 'DaHuy', name='enrollmentstatus'),
               nullable=False,
               comment=None,
               existing_comment='Trạng thái: DaDangKy, DaHuy, ChoDuyet',
               existing_server_default=sa.text("'DaDangKy'::character varying"))
    op.alter_column('DangKy', 'LanDangKy',
               existing_type=sa.INTEGER(),
               nullable=False,
               comment=None,
               existing_comment='Lần đăng ký',
               existing_server_default=sa.text('1'))
    op.alter_column('DangKy', 'GhiChu',
               existing_type=sa.VARCHAR(length=200),
               comment=None,
               existing_comment='Ghi chú',
               existing_nullable=True)
    op.drop_constraint(op.f('uq_dk_sv_lophp'), 'DangKy', type_='unique')
    op.create_index(op.f('ix_DangKy_MaDangKy'), 'DangKy', ['MaDangKy'], unique=False)
    op.drop_constraint(op.f('fk_dk_sv'), 'DangKy', type_='foreignkey')
    op.drop_table_comment(
        'DangKy',
        existing_comment='Đăng ký học phần - PHÂN MẢNH theo cơ sở MỞ LỚP',
        schema=None
    )
    op.alter_column('GiangVien', 'MaGV',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='Mã giảng viên',
               existing_nullable=False)
    op.alter_column('GiangVien', 'userId',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='ID người dùng liên kết',
               existing_nullable=False)
    op.alter_column('GiangVien', 'Ho',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='Họ',
               existing_nullable=False)
    op.alter_column('GiangVien', 'Ten',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='Tên',
               existing_nullable=False)
    op.alter_column('GiangVien', 'NgaySinh',
               existing_type=sa.DATE(),
               comment=None,
               existing_comment='Ngày sinh',
               existing_nullable=True)
    op.alter_column('GiangVien', 'GioiTinh',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.Enum('Nam', 'Nu', 'Khac', name='genders'),
               comment=None,
               existing_comment='Giới tính: Nam, Nu, Khac',
               existing_nullable=True,
               existing_server_default=sa.text("'Khac'::character varying"))
    op.alter_column('GiangVien', 'HocVi',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='Học vị: CN, ThS, TS',
               existing_nullable=True)
    op.alter_column('GiangVien', 'HocHam',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='Học hàm: GTV, PGS, GS',
               existing_nullable=True)
    op.alter_column('GiangVien', 'SDT',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='Số điện thoại',
               existing_nullable=True)
    op.alter_column('GiangVien', 'DiaChi',
               existing_type=sa.VARCHAR(length=300),
               comment=None,
               existing_comment='Địa chỉ',
               existing_nullable=True)
    op.alter_column('GiangVien', 'MaCoSo',
               existing_type=sa.VARCHAR(length=10),
               comment=None,
               existing_comment='Cơ sở quản lý chính',
               existing_nullable=False,
               existing_server_default=sa.text("'HADONG'::character varying"))
    op.alter_column('GiangVien', 'MaKhoa',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='Khoa phụ trách',
               existing_nullable=True)
    op.alter_column('GiangVien', 'TrangThai',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('DangCongTac', 'TamNghi', 'NghiViec', name='teacherstatus'),
               comment=None,
               existing_comment='Trạng thái: DangCongTac, TamNghi, NghiViec',
               existing_nullable=True,
               existing_server_default=sa.text("'DangCongTac'::character varying"))
    op.alter_column('GiangVien', 'NgayTao',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.String(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.create_index(op.f('ix_GiangVien_MaGV'), 'GiangVien', ['MaGV'], unique=False)
    op.drop_constraint(op.f('fk_gv_coso'), 'GiangVien', type_='foreignkey')
    op.drop_constraint(op.f('fk_gv_khoa'), 'GiangVien', type_='foreignkey')
    op.drop_table_comment(
        'GiangVien',
        existing_comment='Giảng viên cơ sở HADONG - PHÂN MẢNH NGANG theo MaCoSo',
        schema=None
    )
    op.alter_column('HocKy', 'MaHocKy',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='Mã học kỳ',
               existing_nullable=False)
    op.alter_column('HocKy', 'NamHoc',
               existing_type=sa.VARCHAR(length=10),
               comment=None,
               existing_comment='Năm học (VD: 2025-2026)',
               existing_nullable=False)
    op.alter_column('HocKy', 'KySo',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Kỳ số: 1, 2, 3',
               existing_nullable=False)
    op.alter_column('HocKy', 'NgayBatDau',
               existing_type=sa.DATE(),
               comment=None,
               existing_comment='Ngày bắt đầu',
               existing_nullable=True)
    op.alter_column('HocKy', 'NgayKetThuc',
               existing_type=sa.DATE(),
               comment=None,
               existing_comment='Ngày kết thúc',
               existing_nullable=True)
    op.alter_column('HocKy', 'TrangThaiHocKy',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('SapMo', 'DangDangKy', 'DangHoc', 'DaKetThuc', name='semesterstatus'),
               nullable=False,
               comment=None,
               existing_comment='Trạng thái: SapMo, DangDangKy, DangHoc, DaKetThuc',
               existing_server_default=sa.text("'SapMo'::character varying"))
    op.create_index(op.f('ix_HocKy_MaHocKy'), 'HocKy', ['MaHocKy'], unique=False)
    op.drop_table_comment(
        'HocKy',
        existing_comment='Thông tin học kỳ - NHÂN BẢN toàn phần tại cả 3 site',
        schema=None
    )
    op.alter_column('HocPhan', 'MaHP',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='Mã học phần',
               existing_nullable=False)
    op.alter_column('HocPhan', 'TenHP',
               existing_type=sa.VARCHAR(length=200),
               comment=None,
               existing_comment='Tên học phần',
               existing_nullable=False)
    op.alter_column('HocPhan', 'SoTinChi',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Số tín chỉ',
               existing_nullable=False)
    op.alter_column('HocPhan', 'SoTietLyThuyet',
               existing_type=sa.INTEGER(),
               nullable=False,
               comment=None,
               existing_comment='Số tiết lý thuyết',
               existing_server_default=sa.text('0'))
    op.alter_column('HocPhan', 'SoTietThucHanh',
               existing_type=sa.INTEGER(),
               nullable=False,
               comment=None,
               existing_comment='Số tiết thực hành',
               existing_server_default=sa.text('0'))
    op.alter_column('HocPhan', 'LoaiHocPhan',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('BatBuoc', 'TuChon', name='coursetype'),
               nullable=False,
               comment=None,
               existing_comment='Loại: BatBuoc, TuChon',
               existing_server_default=sa.text("'BatBuoc'::character varying"))
    op.alter_column('HocPhan', 'MaKhoa',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='Mã khoa phụ trách',
               existing_nullable=False)
    op.alter_column('HocPhan', 'MoTa',
               existing_type=sa.VARCHAR(length=1000),
               comment=None,
               existing_comment='Mô tả nội dung',
               existing_nullable=True)
    op.alter_column('HocPhan', 'TrangThai',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('HoatDong', 'TamDung', 'HuyBo', name='coursestatus'),
               nullable=False,
               comment=None,
               existing_comment='Trạng thái: HoatDong, Khoa',
               existing_server_default=sa.text("'HoatDong'::character varying"))
    op.alter_column('HocPhan', 'NgayTao',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_index(op.f('idx_hocphan_khoa'), table_name='HocPhan')
    op.drop_index(op.f('idx_hocphan_trangthai'), table_name='HocPhan')
    op.create_index(op.f('ix_HocPhan_MaHP'), 'HocPhan', ['MaHP'], unique=False)
    op.drop_table_comment(
        'HocPhan',
        existing_comment='Danh mục học phần - NHÂN BẢN toàn phần tại cả 3 site',
        schema=None
    )
    op.alter_column('Khoa', 'MaKhoa',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='Mã khoa',
               existing_nullable=False)
    op.alter_column('Khoa', 'TenKhoa',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='Tên khoa',
               existing_nullable=False)
    op.alter_column('Khoa', 'MoTa',
               existing_type=sa.VARCHAR(length=500),
               comment=None,
               existing_comment='Mô tả khoa',
               existing_nullable=True)
    op.alter_column('Khoa', 'NgayThanhLap',
               existing_type=sa.DATE(),
               comment=None,
               existing_comment='Ngày thành lập',
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_DATE'))
    op.alter_column('Khoa', 'TrangThai',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('HoatDong', 'NgungHoatDong', name='generalstatus'),
               comment=None,
               existing_comment='Trạng thái: HoatDong, BaoTri',
               existing_nullable=True,
               existing_server_default=sa.text("'HoatDong'::character varying"))
    op.create_index(op.f('ix_Khoa_MaKhoa'), 'Khoa', ['MaKhoa'], unique=False)
    op.drop_table_comment(
        'Khoa',
        existing_comment='Thông tin khoa đào tạo - NHÂN BẢN toàn phần tại cả 3 site',
        schema=None
    )
    op.alter_column('LichHoc', 'MaLich',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='Mã lịch',
               existing_nullable=False)
    op.alter_column('LichHoc', 'MaLopHP',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='Lớp học phần',
               existing_nullable=False)
    op.alter_column('LichHoc', 'MaPhong',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='Phòng học',
               existing_nullable=False)
    op.alter_column('LichHoc', 'ThuTrongTuan',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Thứ: 2=Thứ 2, ..., 8=Chủ nhật',
               existing_nullable=False)
    op.alter_column('LichHoc', 'TietBatDau',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Tiết bắt đầu',
               existing_nullable=False)
    op.alter_column('LichHoc', 'SoTiet',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Số tiết liên tiếp',
               existing_nullable=False)
    op.alter_column('LichHoc', 'NgayBatDau',
               existing_type=sa.DATE(),
               comment=None,
               existing_comment='Ngày bắt đầu học',
               existing_nullable=True)
    op.alter_column('LichHoc', 'NgayKetThuc',
               existing_type=sa.DATE(),
               comment=None,
               existing_comment='Ngày kết thúc học',
               existing_nullable=True)
    op.alter_column('LichHoc', 'GhiChu',
               existing_type=sa.VARCHAR(length=200),
               comment=None,
               existing_comment='Ghi chú',
               existing_nullable=True)
    op.create_index(op.f('ix_LichHoc_MaLich'), 'LichHoc', ['MaLich'], unique=False)
    op.drop_constraint(op.f('fk_lich_lophp'), 'LichHoc', type_='foreignkey')
    op.create_foreign_key(None, 'LichHoc', 'LopHocPhan', ['MaLopHP'], ['MaLopHP'])
    op.drop_table_comment(
        'LichHoc',
        existing_comment='Lịch học - PHÂN MẢNH DẪN XUẤT theo LopHocPhan',
        schema=None
    )
    op.alter_column('LopHocPhan', 'MaLopHP',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='Mã lớp học phần',
               existing_nullable=False)
    op.alter_column('LopHocPhan', 'MaHP',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='Mã học phần',
               existing_nullable=False)
    op.alter_column('LopHocPhan', 'MaHocKy',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='Mã học kỳ',
               existing_nullable=False)
    op.alter_column('LopHocPhan', 'MaCoSo',
               existing_type=sa.VARCHAR(length=10),
               comment=None,
               existing_comment='Cơ sở MỞ LỚP này',
               existing_nullable=False,
               existing_server_default=sa.text("'HADONG'::character varying"))
    op.alter_column('LopHocPhan', 'MaGV',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='Giảng viên phụ trách',
               existing_nullable=False)
    op.alter_column('LopHocPhan', 'TenLopHP',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='Tên hiển thị lớp',
               existing_nullable=True)
    op.alter_column('LopHocPhan', 'SiSoToiDa',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Sĩ số tối đa',
               existing_nullable=False)
    op.alter_column('LopHocPhan', 'SiSoHienTai',
               existing_type=sa.INTEGER(),
               nullable=False,
               comment=None,
               existing_comment='Sĩ số hiện tại',
               existing_server_default=sa.text('0'))
    op.alter_column('LopHocPhan', 'HinhThucHoc',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('Offline', 'Online', 'Hybrid', name='studyform'),
               nullable=False,
               comment=None,
               existing_comment='Hình thức: Offline, Online, Hybrid',
               existing_server_default=sa.text("'Offline'::character varying"))
    op.alter_column('LopHocPhan', 'TrangThaiLop',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('Mo', 'Dong', 'Huy', name='classsectionstatus'),
               nullable=False,
               comment=None,
               existing_comment='Trạng thái: Mo, Dong, Huy',
               existing_server_default=sa.text("'Mo'::character varying"))
    op.alter_column('LopHocPhan', 'NgayTao',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.create_index(op.f('ix_LopHocPhan_MaLopHP'), 'LopHocPhan', ['MaLopHP'], unique=False)
    op.drop_table_comment(
        'LopHocPhan',
        existing_comment='Lớp học phần mở tại HADONG - PHÂN MẢNH theo cơ sở MỞ LỚP',
        schema=None
    )
    op.alter_column('PhongHoc', 'MaPhong',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='Mã phòng',
               existing_nullable=False)
    op.alter_column('PhongHoc', 'TenPhong',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='Tên phòng',
               existing_nullable=False)
    op.alter_column('PhongHoc', 'ToaNha',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='Tòa nhà',
               existing_nullable=True)
    op.alter_column('PhongHoc', 'Tang',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Tầng',
               existing_nullable=True)
    op.alter_column('PhongHoc', 'SucChua',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Sức chứa',
               existing_nullable=False)
    op.alter_column('PhongHoc', 'LoaiPhong',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.Enum('LyThuyet', 'ThucHanh', 'PhongMay', 'MayTinh', 'HoiTruong', 'ThiNghiem', 'Khac', name='roomtype'),
               nullable=False,
               comment=None,
               existing_comment='Loại: LyThuyet, MayTinh, ThiNghiem, HoiTruong',
               existing_server_default=sa.text("'LyThuyet'::character varying"))
    op.alter_column('PhongHoc', 'MaCoSo',
               existing_type=sa.VARCHAR(length=10),
               comment=None,
               existing_comment='Cơ sở sở hữu phòng',
               existing_nullable=False,
               existing_server_default=sa.text("'HADONG'::character varying"))
    op.alter_column('PhongHoc', 'TrangThai',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('HoatDong', 'BaoTri', 'NgungSuDung', name='roomstatus'),
               nullable=False,
               comment=None,
               existing_comment='Trạng thái: HoatDong, BaoTri, NgungSuDung',
               existing_server_default=sa.text("'HoatDong'::character varying"))
    op.alter_column('PhongHoc', 'NgayTao',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.create_index(op.f('ix_PhongHoc_MaPhong'), 'PhongHoc', ['MaPhong'], unique=False)
    op.drop_table_comment(
        'PhongHoc',
        existing_comment='Phòng học cơ sở HADONG - PHÂN MẢNH NGANG theo MaCoSo',
        schema=None
    )
    op.alter_column('SinhVien', 'MaSV',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='Mã sinh viên',
               existing_nullable=False)
    op.alter_column('SinhVien', 'userId',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='ID người dùng liên kết',
               existing_nullable=False)
    op.alter_column('SinhVien', 'Ho',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='Họ',
               existing_nullable=False)
    op.alter_column('SinhVien', 'Ten',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='Tên',
               existing_nullable=False)
    op.alter_column('SinhVien', 'NgaySinh',
               existing_type=sa.DATE(),
               comment=None,
               existing_comment='Ngày sinh',
               existing_nullable=True)
    op.alter_column('SinhVien', 'GioiTinh',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.Enum('Nam', 'Nu', 'Khac', name='genders'),
               comment=None,
               existing_comment='Giới tính: Nam, Nu, Khac',
               existing_nullable=True,
               existing_server_default=sa.text("'Khac'::character varying"))
    op.alter_column('SinhVien', 'SDT',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='Số điện thoại',
               existing_nullable=True)
    op.alter_column('SinhVien', 'DiaChi',
               existing_type=sa.VARCHAR(length=300),
               comment=None,
               existing_comment='Địa chỉ',
               existing_nullable=True)
    op.alter_column('SinhVien', 'MaCoSo',
               existing_type=sa.VARCHAR(length=10),
               comment=None,
               existing_comment='Cơ sở quản lý chính',
               existing_nullable=False,
               existing_server_default=sa.text("'HADONG'::character varying"))
    op.alter_column('SinhVien', 'MaKhoa',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='Khoa sinh viên theo học',
               existing_nullable=True)
    op.alter_column('SinhVien', 'TrangThai',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('DangHoc', 'BaoLuu', 'ThoiHoc', 'TotNghiep', name='studentstatus'),
               comment=None,
               existing_comment='Trạng thái: DangHoc, BaoLuu, ThoiHoc, TotNghiep',
               existing_nullable=True,
               existing_server_default=sa.text("'DangHoc'::character varying"))
    op.alter_column('SinhVien', 'NgayNhapHoc',
               existing_type=sa.DATE(),
               comment=None,
               existing_comment='Ngày nhập học',
               existing_nullable=True)
    op.alter_column('SinhVien', 'NgayTao',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.String(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.create_index(op.f('ix_SinhVien_MaSV'), 'SinhVien', ['MaSV'], unique=False)
    op.drop_constraint(op.f('fk_sv_coso'), 'SinhVien', type_='foreignkey')
    op.drop_constraint(op.f('fk_sv_khoa'), 'SinhVien', type_='foreignkey')
    op.drop_table_comment(
        'SinhVien',
        existing_comment='Sinh viên cơ sở HADONG - PHÂN MẢNH NGANG theo MaCoSo',
        schema=None
    )
    op.alter_column('users', 'userId',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='ID định danh người dùng',
               existing_nullable=False)
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='Tên đăng nhập',
               existing_nullable=False)
    op.alter_column('users', 'password',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='Mật khẩu (đã mã hóa)',
               existing_nullable=False)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=100),
               nullable=False,
               comment=None,
               existing_comment='Email liên lạc')
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('SinhVien', 'GiangVien', 'Admin', name='userrole'),
               comment=None,
               existing_comment='Vai trò: SinhVien, GiangVien, Admin',
               existing_nullable=False)
    op.alter_column('users', 'MaCoSo',
               existing_type=sa.VARCHAR(length=10),
               comment=None,
               existing_comment='Mã cơ sở trực thuộc (Dùng để định tuyến DB)',
               existing_nullable=False)
    op.alter_column('users', 'status',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('Active', 'Inactive', 'Locked', name='userstatus'),
               comment=None,
               existing_comment='Trạng thái tài khoản: Active, Inactive, Locked',
               existing_nullable=True,
               existing_server_default=sa.text("'Active'::character varying"))
    op.alter_column('users', 'NgayTao',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.String(),
               comment=None,
               existing_comment='Ngày tạo tài khoản',
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.create_index(op.f('ix_users_userId'), 'users', ['userId'], unique=False)
    op.drop_constraint(op.f('fk_users_coso'), 'users', type_='foreignkey')
    op.drop_table_comment(
        'users',
        existing_comment='Thông tin người dùng hệ thống - NHÂN BẢN toàn phần tại cả 3 site',
        schema=None
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table_comment(
        'users',
        'Thông tin người dùng hệ thống - NHÂN BẢN toàn phần tại cả 3 site',
        existing_comment=None,
        schema=None
    )
    op.create_foreign_key(op.f('fk_users_coso'), 'users', 'CoSo', ['MaCoSo'], ['MaCoSo'])
    op.drop_index(op.f('ix_users_userId'), table_name='users')
    op.alter_column('users', 'NgayTao',
               existing_type=sa.String(),
               type_=postgresql.TIMESTAMP(),
               comment='Ngày tạo tài khoản',
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('users', 'status',
               existing_type=sa.Enum('Active', 'Inactive', 'Locked', name='userstatus'),
               type_=sa.VARCHAR(length=20),
               comment='Trạng thái tài khoản: Active, Inactive, Locked',
               existing_nullable=True,
               existing_server_default=sa.text("'Active'::character varying"))
    op.alter_column('users', 'MaCoSo',
               existing_type=sa.VARCHAR(length=10),
               comment='Mã cơ sở trực thuộc (Dùng để định tuyến DB)',
               existing_nullable=False)
    op.alter_column('users', 'role',
               existing_type=sa.Enum('SinhVien', 'GiangVien', 'Admin', name='userrole'),
               type_=sa.VARCHAR(length=20),
               comment='Vai trò: SinhVien, GiangVien, Admin',
               existing_nullable=False)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=100),
               nullable=True,
               comment='Email liên lạc')
    op.alter_column('users', 'password',
               existing_type=sa.VARCHAR(length=255),
               comment='Mật khẩu (đã mã hóa)',
               existing_nullable=False)
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(length=50),
               comment='Tên đăng nhập',
               existing_nullable=False)
    op.alter_column('users', 'userId',
               existing_type=sa.VARCHAR(length=50),
               comment='ID định danh người dùng',
               existing_nullable=False)
    op.create_table_comment(
        'SinhVien',
        'Sinh viên cơ sở HADONG - PHÂN MẢNH NGANG theo MaCoSo',
        existing_comment=None,
        schema=None
    )
    op.create_foreign_key(op.f('fk_sv_khoa'), 'SinhVien', 'Khoa', ['MaKhoa'], ['MaKhoa'])
    op.create_foreign_key(op.f('fk_sv_coso'), 'SinhVien', 'CoSo', ['MaCoSo'], ['MaCoSo'])
    op.drop_index(op.f('ix_SinhVien_MaSV'), table_name='SinhVien')
    op.alter_column('SinhVien', 'NgayTao',
               existing_type=sa.String(),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('SinhVien', 'NgayNhapHoc',
               existing_type=sa.DATE(),
               comment='Ngày nhập học',
               existing_nullable=True)
    op.alter_column('SinhVien', 'TrangThai',
               existing_type=sa.Enum('DangHoc', 'BaoLuu', 'ThoiHoc', 'TotNghiep', name='studentstatus'),
               type_=sa.VARCHAR(length=20),
               comment='Trạng thái: DangHoc, BaoLuu, ThoiHoc, TotNghiep',
               existing_nullable=True,
               existing_server_default=sa.text("'DangHoc'::character varying"))
    op.alter_column('SinhVien', 'MaKhoa',
               existing_type=sa.VARCHAR(length=20),
               comment='Khoa sinh viên theo học',
               existing_nullable=True)
    op.alter_column('SinhVien', 'MaCoSo',
               existing_type=sa.VARCHAR(length=10),
               comment='Cơ sở quản lý chính',
               existing_nullable=False,
               existing_server_default=sa.text("'HADONG'::character varying"))
    op.alter_column('SinhVien', 'DiaChi',
               existing_type=sa.VARCHAR(length=300),
               comment='Địa chỉ',
               existing_nullable=True)
    op.alter_column('SinhVien', 'SDT',
               existing_type=sa.VARCHAR(length=20),
               comment='Số điện thoại',
               existing_nullable=True)
    op.alter_column('SinhVien', 'GioiTinh',
               existing_type=sa.Enum('Nam', 'Nu', 'Khac', name='genders'),
               type_=sa.VARCHAR(length=10),
               comment='Giới tính: Nam, Nu, Khac',
               existing_nullable=True,
               existing_server_default=sa.text("'Khac'::character varying"))
    op.alter_column('SinhVien', 'NgaySinh',
               existing_type=sa.DATE(),
               comment='Ngày sinh',
               existing_nullable=True)
    op.alter_column('SinhVien', 'Ten',
               existing_type=sa.VARCHAR(length=50),
               comment='Tên',
               existing_nullable=False)
    op.alter_column('SinhVien', 'Ho',
               existing_type=sa.VARCHAR(length=50),
               comment='Họ',
               existing_nullable=False)
    op.alter_column('SinhVien', 'userId',
               existing_type=sa.VARCHAR(length=50),
               comment='ID người dùng liên kết',
               existing_nullable=False)
    op.alter_column('SinhVien', 'MaSV',
               existing_type=sa.VARCHAR(length=20),
               comment='Mã sinh viên',
               existing_nullable=False)
    op.create_table_comment(
        'PhongHoc',
        'Phòng học cơ sở HADONG - PHÂN MẢNH NGANG theo MaCoSo',
        existing_comment=None,
        schema=None
    )
    op.drop_index(op.f('ix_PhongHoc_MaPhong'), table_name='PhongHoc')
    op.alter_column('PhongHoc', 'NgayTao',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('PhongHoc', 'TrangThai',
               existing_type=sa.Enum('HoatDong', 'BaoTri', 'NgungSuDung', name='roomstatus'),
               type_=sa.VARCHAR(length=20),
               nullable=True,
               comment='Trạng thái: HoatDong, BaoTri, NgungSuDung',
               existing_server_default=sa.text("'HoatDong'::character varying"))
    op.alter_column('PhongHoc', 'MaCoSo',
               existing_type=sa.VARCHAR(length=10),
               comment='Cơ sở sở hữu phòng',
               existing_nullable=False,
               existing_server_default=sa.text("'HADONG'::character varying"))
    op.alter_column('PhongHoc', 'LoaiPhong',
               existing_type=sa.Enum('LyThuyet', 'ThucHanh', 'PhongMay', 'MayTinh', 'HoiTruong', 'ThiNghiem', 'Khac', name='roomtype'),
               type_=sa.VARCHAR(length=30),
               nullable=True,
               comment='Loại: LyThuyet, MayTinh, ThiNghiem, HoiTruong',
               existing_server_default=sa.text("'LyThuyet'::character varying"))
    op.alter_column('PhongHoc', 'SucChua',
               existing_type=sa.INTEGER(),
               comment='Sức chứa',
               existing_nullable=False)
    op.alter_column('PhongHoc', 'Tang',
               existing_type=sa.INTEGER(),
               comment='Tầng',
               existing_nullable=True)
    op.alter_column('PhongHoc', 'ToaNha',
               existing_type=sa.VARCHAR(length=50),
               comment='Tòa nhà',
               existing_nullable=True)
    op.alter_column('PhongHoc', 'TenPhong',
               existing_type=sa.VARCHAR(length=100),
               comment='Tên phòng',
               existing_nullable=False)
    op.alter_column('PhongHoc', 'MaPhong',
               existing_type=sa.VARCHAR(length=20),
               comment='Mã phòng',
               existing_nullable=False)
    op.create_table_comment(
        'LopHocPhan',
        'Lớp học phần mở tại HADONG - PHÂN MẢNH theo cơ sở MỞ LỚP',
        existing_comment=None,
        schema=None
    )
    op.drop_index(op.f('ix_LopHocPhan_MaLopHP'), table_name='LopHocPhan')
    op.alter_column('LopHocPhan', 'NgayTao',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('LopHocPhan', 'TrangThaiLop',
               existing_type=sa.Enum('Mo', 'Dong', 'Huy', name='classsectionstatus'),
               type_=sa.VARCHAR(length=20),
               nullable=True,
               comment='Trạng thái: Mo, Dong, Huy',
               existing_server_default=sa.text("'Mo'::character varying"))
    op.alter_column('LopHocPhan', 'HinhThucHoc',
               existing_type=sa.Enum('Offline', 'Online', 'Hybrid', name='studyform'),
               type_=sa.VARCHAR(length=20),
               nullable=True,
               comment='Hình thức: Offline, Online, Hybrid',
               existing_server_default=sa.text("'Offline'::character varying"))
    op.alter_column('LopHocPhan', 'SiSoHienTai',
               existing_type=sa.INTEGER(),
               nullable=True,
               comment='Sĩ số hiện tại',
               existing_server_default=sa.text('0'))
    op.alter_column('LopHocPhan', 'SiSoToiDa',
               existing_type=sa.INTEGER(),
               comment='Sĩ số tối đa',
               existing_nullable=False)
    op.alter_column('LopHocPhan', 'TenLopHP',
               existing_type=sa.VARCHAR(length=100),
               comment='Tên hiển thị lớp',
               existing_nullable=True)
    op.alter_column('LopHocPhan', 'MaGV',
               existing_type=sa.VARCHAR(length=20),
               comment='Giảng viên phụ trách',
               existing_nullable=False)
    op.alter_column('LopHocPhan', 'MaCoSo',
               existing_type=sa.VARCHAR(length=10),
               comment='Cơ sở MỞ LỚP này',
               existing_nullable=False,
               existing_server_default=sa.text("'HADONG'::character varying"))
    op.alter_column('LopHocPhan', 'MaHocKy',
               existing_type=sa.VARCHAR(length=20),
               comment='Mã học kỳ',
               existing_nullable=False)
    op.alter_column('LopHocPhan', 'MaHP',
               existing_type=sa.VARCHAR(length=20),
               comment='Mã học phần',
               existing_nullable=False)
    op.alter_column('LopHocPhan', 'MaLopHP',
               existing_type=sa.VARCHAR(length=20),
               comment='Mã lớp học phần',
               existing_nullable=False)
    op.create_table_comment(
        'LichHoc',
        'Lịch học - PHÂN MẢNH DẪN XUẤT theo LopHocPhan',
        existing_comment=None,
        schema=None
    )
    op.drop_constraint(None, 'LichHoc', type_='foreignkey')
    op.create_foreign_key(op.f('fk_lich_lophp'), 'LichHoc', 'LopHocPhan', ['MaLopHP'], ['MaLopHP'], ondelete='CASCADE')
    op.drop_index(op.f('ix_LichHoc_MaLich'), table_name='LichHoc')
    op.alter_column('LichHoc', 'GhiChu',
               existing_type=sa.VARCHAR(length=200),
               comment='Ghi chú',
               existing_nullable=True)
    op.alter_column('LichHoc', 'NgayKetThuc',
               existing_type=sa.DATE(),
               comment='Ngày kết thúc học',
               existing_nullable=True)
    op.alter_column('LichHoc', 'NgayBatDau',
               existing_type=sa.DATE(),
               comment='Ngày bắt đầu học',
               existing_nullable=True)
    op.alter_column('LichHoc', 'SoTiet',
               existing_type=sa.INTEGER(),
               comment='Số tiết liên tiếp',
               existing_nullable=False)
    op.alter_column('LichHoc', 'TietBatDau',
               existing_type=sa.INTEGER(),
               comment='Tiết bắt đầu',
               existing_nullable=False)
    op.alter_column('LichHoc', 'ThuTrongTuan',
               existing_type=sa.INTEGER(),
               comment='Thứ: 2=Thứ 2, ..., 8=Chủ nhật',
               existing_nullable=False)
    op.alter_column('LichHoc', 'MaPhong',
               existing_type=sa.VARCHAR(length=20),
               comment='Phòng học',
               existing_nullable=False)
    op.alter_column('LichHoc', 'MaLopHP',
               existing_type=sa.VARCHAR(length=20),
               comment='Lớp học phần',
               existing_nullable=False)
    op.alter_column('LichHoc', 'MaLich',
               existing_type=sa.VARCHAR(length=20),
               comment='Mã lịch',
               existing_nullable=False)
    op.create_table_comment(
        'Khoa',
        'Thông tin khoa đào tạo - NHÂN BẢN toàn phần tại cả 3 site',
        existing_comment=None,
        schema=None
    )
    op.drop_index(op.f('ix_Khoa_MaKhoa'), table_name='Khoa')
    op.alter_column('Khoa', 'TrangThai',
               existing_type=sa.Enum('HoatDong', 'NgungHoatDong', name='generalstatus'),
               type_=sa.VARCHAR(length=20),
               comment='Trạng thái: HoatDong, BaoTri',
               existing_nullable=True,
               existing_server_default=sa.text("'HoatDong'::character varying"))
    op.alter_column('Khoa', 'NgayThanhLap',
               existing_type=sa.DATE(),
               comment='Ngày thành lập',
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_DATE'))
    op.alter_column('Khoa', 'MoTa',
               existing_type=sa.VARCHAR(length=500),
               comment='Mô tả khoa',
               existing_nullable=True)
    op.alter_column('Khoa', 'TenKhoa',
               existing_type=sa.VARCHAR(length=100),
               comment='Tên khoa',
               existing_nullable=False)
    op.alter_column('Khoa', 'MaKhoa',
               existing_type=sa.VARCHAR(length=20),
               comment='Mã khoa',
               existing_nullable=False)
    op.create_table_comment(
        'HocPhan',
        'Danh mục học phần - NHÂN BẢN toàn phần tại cả 3 site',
        existing_comment=None,
        schema=None
    )
    op.drop_index(op.f('ix_HocPhan_MaHP'), table_name='HocPhan')
    op.create_index(op.f('idx_hocphan_trangthai'), 'HocPhan', ['TrangThai'], unique=False)
    op.create_index(op.f('idx_hocphan_khoa'), 'HocPhan', ['MaKhoa'], unique=False)
    op.alter_column('HocPhan', 'NgayTao',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('HocPhan', 'TrangThai',
               existing_type=sa.Enum('HoatDong', 'TamDung', 'HuyBo', name='coursestatus'),
               type_=sa.VARCHAR(length=20),
               nullable=True,
               comment='Trạng thái: HoatDong, Khoa',
               existing_server_default=sa.text("'HoatDong'::character varying"))
    op.alter_column('HocPhan', 'MoTa',
               existing_type=sa.VARCHAR(length=1000),
               comment='Mô tả nội dung',
               existing_nullable=True)
    op.alter_column('HocPhan', 'MaKhoa',
               existing_type=sa.VARCHAR(length=20),
               comment='Mã khoa phụ trách',
               existing_nullable=False)
    op.alter_column('HocPhan', 'LoaiHocPhan',
               existing_type=sa.Enum('BatBuoc', 'TuChon', name='coursetype'),
               type_=sa.VARCHAR(length=20),
               nullable=True,
               comment='Loại: BatBuoc, TuChon',
               existing_server_default=sa.text("'BatBuoc'::character varying"))
    op.alter_column('HocPhan', 'SoTietThucHanh',
               existing_type=sa.INTEGER(),
               nullable=True,
               comment='Số tiết thực hành',
               existing_server_default=sa.text('0'))
    op.alter_column('HocPhan', 'SoTietLyThuyet',
               existing_type=sa.INTEGER(),
               nullable=True,
               comment='Số tiết lý thuyết',
               existing_server_default=sa.text('0'))
    op.alter_column('HocPhan', 'SoTinChi',
               existing_type=sa.INTEGER(),
               comment='Số tín chỉ',
               existing_nullable=False)
    op.alter_column('HocPhan', 'TenHP',
               existing_type=sa.VARCHAR(length=200),
               comment='Tên học phần',
               existing_nullable=False)
    op.alter_column('HocPhan', 'MaHP',
               existing_type=sa.VARCHAR(length=20),
               comment='Mã học phần',
               existing_nullable=False)
    op.create_table_comment(
        'HocKy',
        'Thông tin học kỳ - NHÂN BẢN toàn phần tại cả 3 site',
        existing_comment=None,
        schema=None
    )
    op.drop_index(op.f('ix_HocKy_MaHocKy'), table_name='HocKy')
    op.alter_column('HocKy', 'TrangThaiHocKy',
               existing_type=sa.Enum('SapMo', 'DangDangKy', 'DangHoc', 'DaKetThuc', name='semesterstatus'),
               type_=sa.VARCHAR(length=20),
               nullable=True,
               comment='Trạng thái: SapMo, DangDangKy, DangHoc, DaKetThuc',
               existing_server_default=sa.text("'SapMo'::character varying"))
    op.alter_column('HocKy', 'NgayKetThuc',
               existing_type=sa.DATE(),
               comment='Ngày kết thúc',
               existing_nullable=True)
    op.alter_column('HocKy', 'NgayBatDau',
               existing_type=sa.DATE(),
               comment='Ngày bắt đầu',
               existing_nullable=True)
    op.alter_column('HocKy', 'KySo',
               existing_type=sa.INTEGER(),
               comment='Kỳ số: 1, 2, 3',
               existing_nullable=False)
    op.alter_column('HocKy', 'NamHoc',
               existing_type=sa.VARCHAR(length=10),
               comment='Năm học (VD: 2025-2026)',
               existing_nullable=False)
    op.alter_column('HocKy', 'MaHocKy',
               existing_type=sa.VARCHAR(length=20),
               comment='Mã học kỳ',
               existing_nullable=False)
    op.create_table_comment(
        'GiangVien',
        'Giảng viên cơ sở HADONG - PHÂN MẢNH NGANG theo MaCoSo',
        existing_comment=None,
        schema=None
    )
    op.create_foreign_key(op.f('fk_gv_khoa'), 'GiangVien', 'Khoa', ['MaKhoa'], ['MaKhoa'])
    op.create_foreign_key(op.f('fk_gv_coso'), 'GiangVien', 'CoSo', ['MaCoSo'], ['MaCoSo'])
    op.drop_index(op.f('ix_GiangVien_MaGV'), table_name='GiangVien')
    op.alter_column('GiangVien', 'NgayTao',
               existing_type=sa.String(),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('GiangVien', 'TrangThai',
               existing_type=sa.Enum('DangCongTac', 'TamNghi', 'NghiViec', name='teacherstatus'),
               type_=sa.VARCHAR(length=20),
               comment='Trạng thái: DangCongTac, TamNghi, NghiViec',
               existing_nullable=True,
               existing_server_default=sa.text("'DangCongTac'::character varying"))
    op.alter_column('GiangVien', 'MaKhoa',
               existing_type=sa.VARCHAR(length=20),
               comment='Khoa phụ trách',
               existing_nullable=True)
    op.alter_column('GiangVien', 'MaCoSo',
               existing_type=sa.VARCHAR(length=10),
               comment='Cơ sở quản lý chính',
               existing_nullable=False,
               existing_server_default=sa.text("'HADONG'::character varying"))
    op.alter_column('GiangVien', 'DiaChi',
               existing_type=sa.VARCHAR(length=300),
               comment='Địa chỉ',
               existing_nullable=True)
    op.alter_column('GiangVien', 'SDT',
               existing_type=sa.VARCHAR(length=20),
               comment='Số điện thoại',
               existing_nullable=True)
    op.alter_column('GiangVien', 'HocHam',
               existing_type=sa.VARCHAR(length=50),
               comment='Học hàm: GTV, PGS, GS',
               existing_nullable=True)
    op.alter_column('GiangVien', 'HocVi',
               existing_type=sa.VARCHAR(length=50),
               comment='Học vị: CN, ThS, TS',
               existing_nullable=True)
    op.alter_column('GiangVien', 'GioiTinh',
               existing_type=sa.Enum('Nam', 'Nu', 'Khac', name='genders'),
               type_=sa.VARCHAR(length=10),
               comment='Giới tính: Nam, Nu, Khac',
               existing_nullable=True,
               existing_server_default=sa.text("'Khac'::character varying"))
    op.alter_column('GiangVien', 'NgaySinh',
               existing_type=sa.DATE(),
               comment='Ngày sinh',
               existing_nullable=True)
    op.alter_column('GiangVien', 'Ten',
               existing_type=sa.VARCHAR(length=50),
               comment='Tên',
               existing_nullable=False)
    op.alter_column('GiangVien', 'Ho',
               existing_type=sa.VARCHAR(length=50),
               comment='Họ',
               existing_nullable=False)
    op.alter_column('GiangVien', 'userId',
               existing_type=sa.VARCHAR(length=50),
               comment='ID người dùng liên kết',
               existing_nullable=False)
    op.alter_column('GiangVien', 'MaGV',
               existing_type=sa.VARCHAR(length=20),
               comment='Mã giảng viên',
               existing_nullable=False)
    op.create_table_comment(
        'DangKy',
        'Đăng ký học phần - PHÂN MẢNH theo cơ sở MỞ LỚP',
        existing_comment=None,
        schema=None
    )
    op.create_foreign_key(op.f('fk_dk_sv'), 'DangKy', 'SinhVien', ['MaSV'], ['MaSV'])
    op.drop_index(op.f('ix_DangKy_MaDangKy'), table_name='DangKy')
    op.create_unique_constraint(op.f('uq_dk_sv_lophp'), 'DangKy', ['MaSV', 'MaLopHP'], postgresql_nulls_not_distinct=False)
    op.alter_column('DangKy', 'GhiChu',
               existing_type=sa.VARCHAR(length=200),
               comment='Ghi chú',
               existing_nullable=True)
    op.alter_column('DangKy', 'LanDangKy',
               existing_type=sa.INTEGER(),
               nullable=True,
               comment='Lần đăng ký',
               existing_server_default=sa.text('1'))
    op.alter_column('DangKy', 'TrangThaiDangKy',
               existing_type=sa.Enum('DaDangKy', 'HoanThanh', 'DaHuy', name='enrollmentstatus'),
               type_=sa.VARCHAR(length=20),
               nullable=True,
               comment='Trạng thái: DaDangKy, DaHuy, ChoDuyet',
               existing_server_default=sa.text("'DaDangKy'::character varying"))
    op.alter_column('DangKy', 'NgayDangKy',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               comment='Thời điểm đăng ký',
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('DangKy', 'MaHocKy',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('DangKy', 'MaHP',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('DangKy', 'MaLopHP',
               existing_type=sa.VARCHAR(length=20),
               comment='Lớp học phần đăng ký',
               existing_nullable=False)
    op.alter_column('DangKy', 'MaSV',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               comment='Sinh viên đăng ký')
    op.alter_column('DangKy', 'userId',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('DangKy', 'MaDangKy',
               existing_type=sa.INTEGER(),
               comment='Mã đăng ký',
               existing_nullable=False,
               autoincrement=True)
    op.create_table_comment(
        'CoSo',
        'Thông tin cơ sở đào tạo - NHÂN BẢN toàn phần tại cả 3 site',
        existing_comment=None,
        schema=None
    )
    op.drop_index(op.f('ix_CoSo_MaCoSo'), table_name='CoSo')
    op.create_unique_constraint(op.f('CoSo_Email_key'), 'CoSo', ['Email'], postgresql_nulls_not_distinct=False)
    op.alter_column('CoSo', 'TrangThai',
               existing_type=sa.Enum('HoatDong', 'NgungHoatDong', name='generalstatus'),
               type_=sa.VARCHAR(length=20),
               comment='Trạng thái: HoatDong, BaoTri, NgungSuDung',
               existing_nullable=True,
               existing_server_default=sa.text("'HoatDong'::character varying"))
    op.alter_column('CoSo', 'NgayThanhLap',
               existing_type=sa.DATE(),
               comment='Ngày thành lập',
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_DATE'))
    op.alter_column('CoSo', 'Email',
               existing_type=sa.VARCHAR(length=100),
               comment='Email cơ sở',
               existing_nullable=True)
    op.alter_column('CoSo', 'SoDienThoai',
               existing_type=sa.VARCHAR(length=20),
               comment='Số điện thoại',
               existing_nullable=True)
    op.alter_column('CoSo', 'DiaChi',
               existing_type=sa.VARCHAR(length=200),
               nullable=False,
               comment='Địa chỉ cơ sở')
    op.alter_column('CoSo', 'TenCoSo',
               existing_type=sa.VARCHAR(length=100),
               comment='Tên cơ sở',
               existing_nullable=False)
    op.alter_column('CoSo', 'MaCoSo',
               existing_type=sa.VARCHAR(length=10),
               comment='Mã cơ sở',
               existing_nullable=False)
    op.create_table('AuditLog',
    sa.Column('MaLog', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('BangCapNhat', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('HanhDong', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('BanGhiCu', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('BanGhiMoi', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('NguoiThucHien', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('DiaChiIP', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('ThoiGian', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('MaLog', name=op.f('AuditLog_pkey'))
    )
    op.create_table('TienQuyet',
    sa.Column('MaHP', sa.VARCHAR(length=20), autoincrement=False, nullable=False, comment='Mã học phần chính'),
    sa.Column('MaHP_TienQuyet', sa.VARCHAR(length=20), autoincrement=False, nullable=False, comment='Mã học phần tiên quyết'),
    sa.CheckConstraint('"MaHP"::text <> "MaHP_TienQuyet"::text', name=op.f('chk_tienquyet_khac')),
    sa.ForeignKeyConstraint(['MaHP'], ['HocPhan.MaHP'], name=op.f('fk_tq_hocphan')),
    sa.ForeignKeyConstraint(['MaHP_TienQuyet'], ['HocPhan.MaHP'], name=op.f('fk_tq_tienquyet')),
    sa.PrimaryKeyConstraint('MaHP', 'MaHP_TienQuyet', name=op.f('TienQuyet_pkey')),
    comment='Quan hệ học phần tiên quyết - NHÂN BẢN toàn phần tại cả 3 site'
    )
    op.create_index(op.f('idx_tienquyet_tq'), 'TienQuyet', ['MaHP_TienQuyet'], unique=False)
    op.create_index(op.f('idx_tienquyet_mahp'), 'TienQuyet', ['MaHP'], unique=False)
    op.create_table('DangKyLog',
    sa.Column('MaLog', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('MaSV', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('MaLopHP', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('HanhDong', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('TrangThaiCu', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('TrangThaiMoi', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('KetQua', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('LyDo', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('NguoiThucHien', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('ThoiGian', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('MaLog', name=op.f('DangKyLog_pkey'))
    )
    # ### end Alembic commands ###
