"""add_MaCoSo_to_NhatKyThaoTac

Revision ID: eea5f2ff5d9d
Revises: fa2cd15c40ea
Create Date: 2026-05-11 01:34:45.754998

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'eea5f2ff5d9d'
down_revision: Union[str, Sequence[str], None] = 'fa2cd15c40ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('DangKy_Log', 'Status',
               existing_type=postgresql.ENUM('SUCCESS', 'FAILED', 'PENDING', name='logstatus'),
               nullable=True)
    op.alter_column('DangKy_Log', 'Message',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_index(op.f('ix_DangKy_Log_userId'), table_name='DangKy_Log')
    op.create_foreign_key(None, 'DangKy_Log', 'users', ['userId'], ['userId'])
    op.add_column('NhatKyThaoTac', sa.Column('MaCoSo', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('NhatKyThaoTac', 'MaCoSo')
    op.drop_constraint(None, 'DangKy_Log', type_='foreignkey')
    op.create_index(op.f('ix_DangKy_Log_userId'), 'DangKy_Log', ['userId'], unique=False)
    op.alter_column('DangKy_Log', 'Message',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('DangKy_Log', 'Status',
               existing_type=postgresql.ENUM('SUCCESS', 'FAILED', 'PENDING', name='logstatus'),
               nullable=False)
    # ### end Alembic commands ###
