"""remove_lan_thu

Revision ID: fa2cd15c40ea
Revises: 36c8fb691532
Create Date: 2026-05-04 22:44:15.901444

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fa2cd15c40ea'
down_revision: Union[str, Sequence[str], None] = '36c8fb691532'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('NhatKyThaoTac', 'LanThu')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('NhatKyThaoTac', sa.Column('LanThu', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
